databases:
  - name: teatime
    ipAllowList: []
    databaseName: teatime
    user: tea_time
    plan: free

services:
  - type: web
    plan: free
    name: teatime
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: teatime
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 