databases:
  - name: teatime
    ipAllowList: []
    databaseName: teatime
    user: tea_time

services:
  - type: web
    name: teatime
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: teatime
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false