databases:
  - name: teatime
    databaseName: teatime
    user: mtyuji

services:
  - type: web
    name: teatime
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: teatime
          property: connectionString
      - key: e0b58f9f79f29c998d0585f5bca98614
        sync: false